<?php

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');
$price = $product->getPriceInfo()->getPrice('final_price')->getAmount()->getValue()*100;
$enable = $block->escapeHtml($this->helper('\CreditClick\PriceModule\Helper\Data')->get_enable_catalog_product());
$country = $block->escapeHtml($this->helper('\CreditClick\PriceModule\Helper\Data')->get_country());
$custom_css = $block->escapeHtml($this->helper('\CreditClick\PriceModule\Helper\Data')->get_custom_css());

?>


<?php if ($enable) : ?>

<div class="cc-price-module-catalog_product" data-cc="<?=$price;?>" data-cc-country="<?=$country?>"></div>
<script type="text/javascript">
    require(["jquery","domReady!"], function ($) {
        String.prototype.replaceAll = function(target, replacement) {
            return this.split(target).join(replacement);
        };
        loadCreditClick();
        $(document).ready(function () {
            let price_box = $(this).find('.price-wrapper');
            debugger;
            $(price_box).on('DOMSubtreeModified', function () {
                let price2 = ($('.price', price_box).html() + "").replaceAll('€', '').replaceAll(' ', '').replaceAll('&nbsp;', '').replaceAll('.', '').replaceAll(',', '');
                $('.cc-price-module-catalog_product').attr('data-cc', price2);
                loadCreditClick();
            });
        });
    });
</script>
<style>
    <?=$custom_css;?>
</style>

<?php endif; ?>


