<?php

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');
$price = $product->getPriceInfo()->getPrice('final_price')->getAmount()->getValue()*100;
$enable = $block->escapeHtml($this->helper('\CreditClick\PriceModule\Helper\Data')->get_enable_catalog_product());
$button_type = $block->escapeHtml($this->helper('\CreditClick\PriceModule\Helper\Data')->get_button_type());
$custom_css = $block->escapeHtml($this->helper('\CreditClick\PriceModule\Helper\Data')->get_custom_css());

?>


<?php if ($enable) : ?>

<div class="cc-price-module-catalog_product" data-cc="<?=$price;?>" data-cc-btn="<?=$button_type?>"></div>
<script type="text/javascript">
    require(["jquery","domReady!"], function ($) {
        loadCreditClick();
    });
</script>
<style>
    <?=$custom_css;?>
</style>

<?php endif; ?>


