<?php

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$enable = $block->escapeHtml($this->helper('\CreditClick\PriceModule\Helper\Data')->get_enable_checkout_cart());
$country = $block->escapeHtml($this->helper('\CreditClick\PriceModule\Helper\Data')->get_country());
$custom_css = $block->escapeHtml($this->helper('\CreditClick\PriceModule\Helper\Data')->get_custom_css());
$cart = $objectManager->get('\Magento\Checkout\Model\Cart');
$price = $cart->getQuote()->getGrandTotal() * 100;

?>

<?php if ($enable) : ?>

<div class="cc-price-module-checkout_cart" data-cc="<?=$price;?>" data-cc-country="<?=$country?>"></div>
<script type="text/javascript">
    require(["jquery","domReady!"], function () {
        loadCreditClick();
    });
</script>
<style>
    <?=$custom_css;?>
</style>

<?php endif; ?>